### ISSUE TITLE
Error: Collection "nestjs-prisma" cannot be resolved.

### ISSUE THREAD

**Issue by richoandika** [notiz-dev/nestjs-prisma#17]
Hello there,
Why I got this error? can I use another package manager like yarn for install the package? because installing 'nestjs-prisma' using other package manager it's normal
nestjs version: 8.2.1
```bash
PS C:\Users\richoandika\nestjs> nest add nestjs-prisma
✔ Package installation in progress... ☕
Starting library setup...
Error: Collection "nestjs-prisma" cannot be resolved.
    at NodeModulesEngineHost.resolve (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:75:19)
    at NodeModulesEngineHost._resolveCollectionPath (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:80:37)
    at NodeModulesEngineHost.createCollectionDescription (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:118:27)
    at SchematicEngine._createCollectionDescription (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics\src\engine\engine.js:162:40)
    at SchematicEngine.createCollection (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:43)
    at NodeWorkflow.execute (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics\src\workflow\base.js:101:41)
    at main (C:\Users\richoandika\tmp\nestjs\jam\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:260:14)
    at Object.<anonymous> (C:\Users\richoandika\nestjs\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:370:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

Failed to execute command: node nestjs-prisma:nest-add --sourceRoot="src" C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\@nestjs\cli\bin\nest.js add nestjs-prisma
```

**Comment by marcjulian** [comment]
@richoandika Hi, seems there is an error when using the schematics. I haven't tested it on Windows and not with yarn.

If you want to use the library you can still install it via 

```
yarn add nestjs-prisma
```

**Comment by richoandika** [comment]
> @richoandika Hi, seems there is an error when using the schematics. I haven't tested it on Windows and not with yarn.
> 
> If you want to use the library you can still install it via
> 
> ```
> yarn add nestjs-prisma
> ```

What's the schematics?
Yup, I do with that.

**Comment by marcjulian** [comment]
The schematics installs the library, initializes prisma, adds optionally dockerfile, adds prisma scripts to your package.json

https://github.com/notiz-dev/nestjs-prisma/blob/main/schematics/nestjs-prisma/index.ts#L35-L42

**Comment by richoandika** [comment]
I see, Thank you for replying.
I'll close the issue.
