### ISSUE TITLE
Nest can't resolve dependencies of the PrismaClientExceptionFilter (?, Object). Please make sure that the argument Object at index [0] is available in the AppModule context

### ISSUE THREAD

**Issue by Rubalaine** [notiz-dev/nestjs-prisma#34]
Hi,
I'm getting the following error:
>  Nest can't resolve dependencies of the PrismaClientExceptionFilter (?, Object). Please make sure that the argument Object at index [0] is available in the AppModule context.

It happens when i try to use `PrismaClientExceptionFilter` provider, exactly like in the documentation.

My `main.ts` file:
```typescript
import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { PrismaClientExceptionFilter, PrismaService } from 'nestjs-prisma';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const { httpAdapter } = app.get(HttpAdapterHost);
  app.useGlobalFilters(new PrismaClientExceptionFilter(httpAdapter));

  const prismaService: PrismaService = app.get(PrismaService);
  prismaService.enableShutdownHooks(app);

  await app.listen(process.env.PORT);
}
bootstrap();
```

My `app.module.ts`
```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { WorkspaceModule } from './workspace/workspace.module';
import { AuthModule } from './auth/auth.module';
import { PrismaClientExceptionFilter, PrismaModule } from 'nestjs-prisma';
import { APP_FILTER } from '@nestjs/core';

@Module({
  imports: [
    AuthModule,
    WorkspaceModule,
    PrismaModule.forRoot(),
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_FILTER,
      useClass: PrismaClientExceptionFilter,
    },
  ],
})
export class AppModule {}

```

**Complete error message:**
```
[Nest] 8849  - 09/15/2022, 9:12:02 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the PrismaClientExceptionFilter (?, Object). Please make sure that the argument Object at index [0] is available in the AppModule context.

Potential solutions:
- If Object is a provider, is it part of the current AppModule?
- If Object is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

Error: Nest can't resolve dependencies of the PrismaClientExceptionFilter (?, Object). Please make sure that the argument Object at index [0] is available in the AppModule context.

Potential solutions:
- If Object is a provider, is it part of the current AppModule?
- If Object is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

    at Injector.lookupComponentInParentModules (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/injector.js:241:19)
    at Injector.resolveComponentInstance (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/injector.js:194:33)
    at resolveParam (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/injector.js:116:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/injector.js:131:27)
    at Injector.loadInstance (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/injector.js:57:13)
    at Injector.loadProvider (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/injector.js:84:9)
    at async Promise.all (index 4)
    at InstanceLoader.createInstancesOfProviders (/home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/instance-loader.js:47:9)
    at /home/kelvenrubalaine/Documents/projects/liberty-backend/node_modules/@nestjs/core/injector/instance-loader.js:32:13
```

**Someone help me?**

**Comment by Rubalaine** [comment]
Was not necessary to import the exception filter as provider

**Comment by marcjulian** [comment]
@Rubalaine do you think we could improve the documentation around the exception filter?

**Comment by quinm0** [comment]
What happened here? Was the problem resolved? I'm getting this error and it's not clear what the resolution was

**Comment by marcjulian** [comment]
Did you run `npx prisma generate`? The filter accesses types from the Prisma client.

https://github.com/notiz-dev/nestjs-prisma/blob/738c879920e37b30c88ec9d3afc01da9c263b56c/lib/prisma-client-exception.filter.ts#L9-L19
