### ISSUE TITLE
`response.status is not a function` when using PrismaClientExceptionFilter

### ISSUE THREAD

**Issue by Webbly25** [notiz-dev/nestjs-prisma#58]
I am using graphql and whenever I get any error (duplicate key, not found, ...) I get the following:

```
{
  "data": {},
  "errors": [
    {
      "message": "response.status is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "userCreate"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "TypeError: response.status is not a function",
          "    at ExpressAdapter.reply (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\@nestjs\\platform-express\\adapters\\express-adapter.js:28:22)",
          "    at PrismaClientExceptionFilter.catch (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\@nestjs\\core\\exceptions\\base-exception-filter.js:28:28)",
          "    at PrismaClientExceptionFilter.catchClientKnownRequestError (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\nestjs-prisma\\lib\\prisma-client-exception.filter.ts:88:16)",
          "    at PrismaClientExceptionFilter.catch (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\nestjs-prisma\\lib\\prisma-client-exception.filter.ts:69:19)",
          "    at ExternalExceptionsHandler.invokeCustomFilters (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\@nestjs\\core\\exceptions\\external-exceptions-handler.js:34:32)",
          "    at ExternalExceptionsHandler.next (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\@nestjs\\core\\exceptions\\external-exceptions-handler.js:13:29)",
          "    at Object.userCreate (C:\\Users\\Ryan\\Documents\\Projects\\Rhyno\\nest-rhyno-v2\\node_modules\\@nestjs\\core\\helpers\\external-proxy.js:14:42)"
        ]
      }
    }
  ]
}
```

I tried adding the filter by using `APP_FILTER` in my `app.module.ts` and also by using `app.useGlobalFilters(new PrismaClientExceptionFilter(httpAdapter));`

**Comment by marcjulian** [comment]
Hi @Webbly25 which version are you using? Do you have a reproduction repo?

**Comment by Webbly25** [comment]
I have just made a repo with an example of the error: [Repo](https://github.com/Webbly25/nestjs-prisma-example).
If you run the gql:
```
query User {
  user(id: 9999) {
    name
  }
}
```
You will get the error which should be `User not found`.

nestjs-prisma is version 0.20.0

**Comment by rhazen35** [comment]
@marcjulian @Webbly25 
Can confirm the issue on v0.20.0. 
Downgraded to v0.19.0 and the expected error is shown. 
Seems to me that the issue is in v0.20.0.

**Comment by marcjulian** [comment]
Thank you @Webbly25 for the reproduction repo. I was able to fix the bug and added a [GraphQL Example](https://github.com/notiz-dev/nestjs-prisma/tree/main/examples/graphql) to test it out the in the future.

Please test it out with the latest bug release 

```
npm i nestjs-prisma@0.20.1
```
