### ISSUE TITLE
Custom Prisma Client is not working

### ISSUE THREAD

**Issue by brandoncollins7** [notiz-dev/nestjs-prisma#79]
I am using an nx mono repo and I have my prisma models dumping to a library. So I am trying to integrate this by using a custom prisma client:

`import {PrismaClient} from '@frnt/lending-api/models'

@Global()
@Module({
  imports: [
    CustomPrismaModule.forRoot({
      name: 'PrismaService',
      client: new PrismaClient()
    }),`

But it just seems like it is not working at all because when I run it is looking for the prisma client in node_modules?

`Error: Cannot find module '.prisma/client/index'
Require stack:
- node_modules\.pnpm\@prisma+client@5.0.0_prisma@5.0.0\node_modules\@prisma\client\index.js
- node_modules\.pnpm\nestjs-prisma@0.22.0_@nestjs+common@10.0.2_@prisma+client@5.0.0_prisma@5.0.0\node_modules\nestjs-prisma\dist\prisma.service.js
- node_modules\.pnpm\nestjs-prisma@0.22.0_@nestjs+common@10.0.2_@prisma+client@5.0.0_prisma@5.0.0\node_modules\nestjs-prisma\dist\prisma.module.js
- node_modules\.pnpm\nestjs-prisma@0.22.0_@nestjs+common@10.0.2_@prisma+client@5.0.0_prisma@5.0.0\node_modules\nestjs-prisma\dist\index.js
- dist\apps\lending-api\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.Module._load (node_modules\@nx\js\src\executors\node\node-with-require-overrides.js:18:31)    
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (node_modules\@prisma+client@5.0.0_prisma@5.0.0\node_modules\@prisma\client\index.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.Module._load (node_modules\@nx\js\src\executors\node\node-with-require-overrides.js:18:31)    
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (node_modules\nestjs-prisma\lib\prisma.service.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

`

**Comment by marcjulian** [comment]
Hi @brandoncollins7, how are you accessing the database are you using `CustomPrismaService`? Do you have a reproduction repository, which would be easier to help if i can reproduce it myself.

**Comment by marcjulian** [comment]
I cannot reproduce it atm. Please provide a reproduction repo.

**Comment by tomcastro** [comment]
Hi @marcjulian, I'm having the same issue but with a PNPM and Turborepo monorepo. I am using `CustomPrismaService<PrismaClient>` with my PrismaClient exported from the output.

I have tried both exporting the custom output to node_modules as specified on the documentation as well as on a folder inside my src directory, but it seems that `nestjs-prisma` is trying to import the default `@prisma/client` and it cannot find it (prisma generate creates the Prisma client on the specified custom output). I'm attaching the error:

```
test:start:dev: Error: Cannot find module '.prisma/client/index'
test:start:dev: Require stack:
test:start:dev: - /Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/@prisma/client/index.js
test:start:dev: - /Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/nestjs-prisma@0.22.0_@nestjs+common@10.2.7_@prisma+client@5.4.2_prisma@5.4.2/node_modules/nestjs-prisma/dist/prisma.service.js
test:start:dev: - /Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/nestjs-prisma@0.22.0_@nestjs+common@10.2.7_@prisma+client@5.4.2_prisma@5.4.2/node_modules/nestjs-prisma/dist/prisma.module.js
test:start:dev: - /Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/nestjs-prisma@0.22.0_@nestjs+common@10.2.7_@prisma+client@5.4.2_prisma@5.4.2/node_modules/nestjs-prisma/dist/index.js
test:start:dev: - /Users/tomascastro/Code/org/org-svcs/apps/test/dist/app.module.js
test:start:dev: - /Users/tomascastro/Code/org/org-svcs/apps/test/dist/main.js
test:start:dev:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
test:start:dev:     at Module.Hook.Module.require (/Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/dd-trace@4.17.0/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
test:start:dev:     at require (node:internal/modules/helpers:130:18)
test:start:dev:     at Object.<anonymous> (/Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/@prisma/client/index.js:2:6)
test:start:dev:     at Module._compile (node:internal/modules/cjs/loader:1233:14)
test:start:dev:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
test:start:dev:     at Module.load (node:internal/modules/cjs/loader:1091:32)
test:start:dev:     at Function.Module._load (node:internal/modules/cjs/loader:938:12)
test:start:dev:     at Module.require (node:internal/modules/cjs/loader:1115:19)
test:start:dev:     at Module.Hook.Module.require (/Users/tomascastro/Code/org/org-svcs/node_modules/.pnpm/dd-trace@4.17.0/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
```

```
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/@org/client"
}
```

app.module.ts
```
import { CustomPrismaModule } from 'nestjs-prisma';
import { PrismaClient } from '@org/client';

...
CustomPrismaModule.forRoot({
  name: 'PrismaService',
  client: new PrismaClient(),
  isGlobal: true,
}),
```

I can help providing a small repo to reproduce, but that will take a bit of time. Maybe this can help in the meantime? 😄

**Comment by marcjulian** [comment]
Thanks for the error logs. Looks like `PrismaService`, which is in the package is trying to access the default prisma client. I will add an example and see if I can reproduce the same error.

**Comment by marcjulian** [comment]
It looks like that this is caused because of the `index.ts` exporting all files from the library, even though `PrismaService` is not used it imports from `@prisma/client`.

I guess the import need to change e.g.

```diff
- import { CustomPrismaModule } from 'nestjs-prisma';
+ import { CustomPrismaModule } from 'nestjs-prisma/custom';
```

https://github.com/notiz-dev/nestjs-prisma/blob/a84e24d8f204e978fa1158c1d908a603df62b2fb/lib/index.ts#L1-L4

A current workaround would be to change the imports too

```ts
import { CustomPrismaModule } from 'nestjs-prisma/dist/custom';
import { CustomPrismaService } from 'nestjs-prisma/dist/custom';
```

**Comment by mvp-studio-repo** [comment]
Hi, thanks for the workaround, but it's seem we can't use the PrismaClientExceptionFilter with this (as it's also require prisma/client) 

Do you think it will be possible in the near future to use all the feature with a custom client ? or is there also another workaround for this case ?

**Comment by Krr0ptioN** [comment]
I am facing the same issue, I managed to solve this issue with workaround (thanks to @marcjulian), although I am not sure whether this is a stable or temporary solution. 

My stack: 
- Nx, typescript
- Custom Prisma Client path

**Comment by mvp-studio-repo** [comment]
@Krr0ptioN Could you share / show how you did your workaround ?

**Comment by marcjulian** [comment]
@Valetek have you tried this workaround? https://github.com/notiz-dev/nestjs-prisma/issues/79#issuecomment-1768053972 I think @Krr0ptioN means that workaround.

**Comment by mvp-studio-repo** [comment]
HO yes this one, finally I used the setup for custom config (with prisma module) and everything is working fine, except that I used my own custom FilterException

I did tried this workaround but it's still fail when calling the prismaFilterException

**Comment by marcjulian** [comment]
Yes `PrismaClientExceptionFilter` does not currently work for custom location. I will have a look on a fix for that as well.

**Comment by Krr0ptioN** [comment]
@Valetek [this workaround](https://github.com/notiz-dev/nestjs-prisma/issues/79#issuecomment-1768053972)

**Comment by marcjulian** [comment]
> I am facing the same issue, I managed to solve this issue with workaround (thanks to @marcjulian), although I am not sure whether this is a stable or temporary solution.
> 
> My stack:
> 
> * Nx, typescript
> * Custom Prisma Client path

This is currently a temporary solution. When I have the time I would like to move all exports related to custom prisma service under `nestjs-prisma/custom`.

**Comment by stormsilver** [comment]
I just ran into this problem and the workaround still seems valid, although the path has changed slightly:

```ts
import { CustomPrismaModule } from 'nestjs-prisma/dist/custom';
```

**Comment by domvanrob** [comment]
Same issue here in our Nx monorepo. However, I'm only encountering this when running the built output within Docker:

```
Error: Cannot find module '.prisma/client/default'
Require stack:
- /usr/src/app/node_modules/.pnpm/@prisma+client@6.17.0_prisma@6.17.0_typescript@5.9.3__typescript@5.9.3/node_modules/@prisma/client/default.js
- /usr/src/app/node_modules/.pnpm/nestjs-prisma@0.26.0_@nestjs+common@11.1.6_class-transformer@0.5.1_class-validator@0.14_eb914299da302755114ac01c0bd371fd/node_modules/nestjs-prisma/dist/prisma-client-exception.filter.js
- /usr/src/app/node_modules/.pnpm/nestjs-prisma@0.26.0_@nestjs+common@11.1.6_class-transformer@0.5.1_class-validator@0.14_eb914299da302755114ac01c0bd371fd/node_modules/nestjs-prisma/dist/index.js
- /usr/src/app/main.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at Object.<anonymous> (/usr/src/app/node_modules/.pnpm/@prisma+client@6.17.0_prisma@6.17.0_typescript@5.9.3__typescript@5.9.3/node_modules/@prisma/client/default.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1706:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/.pnpm/@prisma+client@6.17.0_prisma@6.17.0_typescript@5.9.3__typescript@5.9.3/node_modules/@prisma/client/default.js',
    '/usr/src/app/node_modules/.pnpm/nestjs-prisma@0.26.0_@nestjs+common@11.1.6_class-transformer@0.5.1_class-validator@0.14_eb914299da302755114ac01c0bd371fd/node_modules/nestjs-prisma/dist/prisma-client-exception.filter.js',
    '/usr/src/app/node_modules/.pnpm/nestjs-prisma@0.26.0_@nestjs+common@11.1.6_class-transformer@0.5.1_class-validator@0.14_eb914299da302755114ac01c0bd371fd/node_modules/nestjs-prisma/dist/index.js',
    '/usr/src/app/main.js'
```

Using the workaround seems to work, but did require a lot of file changes and disabling of the exception filter.

**Comment by marcjulian** [comment]
Yes unfortunately the build in exception filter doesn't work because it relies on `@prisma/client` import. If you need the filter you can copy it over and adjust the import.

**Comment by domvanrob** [comment]
> Yes unfortunately the build in exception filter doesn't work because it relies on `@prisma/client` import. If you need the filter you can copy it over and adjust the import.

This worked, thanks.

Tried to think about a possible solution for this and if I'm correct, this only needs the: `@Catch(Prisma?.PrismaClientKnownRequestError)` Part of the Prisma client for NestJS to match the error type.

Would a factory function not work, something like:

```
export function createPrismaClientExceptionFilter(
  errorCodesStatusMapping?: ErrorCodesStatusMapping,
  catchError: any = [Prisma?.PrismaClientKnownRequestError]
) {
  @Catch(catchError)
  class PrismaClientExceptionFilter extends BaseExceptionFilter {
    ...
  }
}
```

**Comment by marcjulian** [comment]
I am working on the next release which will only support Prisma v7 with the database adapter and output path.

If you like you can try out `nestjs-prisma@0.28.0-dev`, please refer to #123 for breaking changes and [new docs](https://nestjs-prisma-dev-next.web.app/getting-started/installation/#option-1-use-library).

Please let me know if that solves the issues with `CustomPrismaService` imports and makes it clear how to use it with the latest prisma release.

**Comment by gaetanmaisse** [comment]
@marcjulian I just faced the issue and tried the new version you're cooking `nestjs-prisma@0.28.0-dev`, it's working great on my side and was pretty straightforward (even without checking the new doc). 
Thanks a lot for the time spent on `nestjs-prisma`!

**Comment by marcjulian** [comment]
Thanks for your feedback @gaetanmaisse!
